### PR TITLE
accept this.

### PR DESCRIPTION
**Pull request by morgen-montgomery**

### CODE REVIEW

**Comment by ctide** [comment]
👎

**Comment by morgen-montgomery** [comment]
I reject that rejection.

**Comment by ctide** [comment]
👍

**Comment by morgen-montgomery** [comment]
thank you.

**Comment by w3cj** [comment]
## Missing in your proposal:

### What datastore are you going to use?

## Things to think about and answer with your team:

### react vs react native
- React is for browsers, react native is for building native ios and android apps. 
- They're not exactly interchangable, though there are some third party projects that allow you to use react native components in the browser.
- Decide what your going to use as early as possible.

### Email/Text Invitations
- Look into Twilio for SMS, sendgrid or mailgun for emails.

### Addresses of locations for Scavenger Hunt
- How are you going to verify the entered address and use it for geo-tagging?

### More Thoughts

### Feature list
- There is a lot in there, and given your current MVP, you'll probably be able to get to a few of them.
- Prioritize this list with your team before assigning them out to team members

### Clearly define the users of your app (in Agile these are known as user roles)
- Scavenger Hunt Oraganizer
- Team Captain
- Team Member
- etc.

### Look into Agile and use the User Story format to help guide your development

### Some examples:

#### As a Scavenger Hunt Organizer, I want to create a new scavenger hunt
- Scavenger hunt will include:
  - Name
  - Date, Time, Start Location

#### As a Scavenger Hunt Organizer, I want to add a Clue to an existing scavenger hunt
- Clue will include
  - Description (can be riddle)
  - Location

#### As a Scavenger Hunt Organizer, I want to invite friends to join an existing scavenger hunt
- Invite via SMS
- Invite via Email

#### As a Scavenger Hunt Organizer, I want to designate team captains for an existing scavenger hunt
- Choose from invited members

#### As a Team Captain, I want to choose the members of my team
- Choose from invited members not on another team yet

**Pull request closed without merging**
